//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detallescompra
    {
        public int id_detalles { get; set; }
        public Nullable<int> id_compra { get; set; }
        public Nullable<int> id_pasaje { get; set; }
        public Nullable<double> precio_pasaje { get; set; }
        public Nullable<int> cantidad_compra { get; set; }
        public Nullable<int> total_compra { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Pasaje Pasaje { get; set; }
    }
}
