//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ruta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ruta()
        {
            this.Pasaje = new HashSet<Pasaje>();
        }
    
        public int id_ruta { get; set; }
        public string nombre_ruta { get; set; }
        public string descripcion_ruta { get; set; }
        public Nullable<int> inicio_ruta { get; set; }
        public Nullable<int> llegada_ruta { get; set; }
        public int id_vehiculo { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
        public virtual Sucursal Sucursal1 { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pasaje> Pasaje { get; set; }
    }
}
